//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 

namespace WS.Service
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback obtenerConfiguracionActualOperationCompleted;

        private System.Threading.SendOrPostCallback obtenerTemaActualOperationCompleted;

        private System.Threading.SendOrPostCallback obtenerOperadorActualOperationCompleted;

        /// <remarks/>
        public Service()
        {
            //this.Url = "http://demosdata.nextel.com.pe/service_configuration/Service.asmx";
            this.Url = System.Configuration.ConfigurationManager.AppSettings["url_web_service"].ToString();
        }

        /// <remarks/>
        public event obtenerConfiguracionActualCompletedEventHandler obtenerConfiguracionActualCompleted;

        /// <remarks/>
        public event obtenerTemaActualCompletedEventHandler obtenerTemaActualCompleted;

        /// <remarks/>
        public event obtenerOperadorActualCompletedEventHandler obtenerOperadorActualCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerConfiguracionActual", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obtenerConfiguracionActual()
        {
            object[] results = this.Invoke("obtenerConfiguracionActual", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginobtenerConfiguracionActual(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("obtenerConfiguracionActual", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndobtenerConfiguracionActual(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void obtenerConfiguracionActualAsync()
        {
            this.obtenerConfiguracionActualAsync(null);
        }

        /// <remarks/>
        public void obtenerConfiguracionActualAsync(object userState)
        {
            if ((this.obtenerConfiguracionActualOperationCompleted == null))
            {
                this.obtenerConfiguracionActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerConfiguracionActualOperationCompleted);
            }
            this.InvokeAsync("obtenerConfiguracionActual", new object[0], this.obtenerConfiguracionActualOperationCompleted, userState);
        }

        private void OnobtenerConfiguracionActualOperationCompleted(object arg)
        {
            if ((this.obtenerConfiguracionActualCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerConfiguracionActualCompleted(this, new obtenerConfiguracionActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerTemaActual", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obtenerTemaActual()
        {
            object[] results = this.Invoke("obtenerTemaActual", new object[0]);
            return ((string)(results[0]));
            //return "0";
        }

        /// <remarks/>
        public System.IAsyncResult BeginobtenerTemaActual(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("obtenerTemaActual", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndobtenerTemaActual(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void obtenerTemaActualAsync()
        {
            this.obtenerTemaActualAsync(null);
        }

        /// <remarks/>
        public void obtenerTemaActualAsync(object userState)
        {
            if ((this.obtenerTemaActualOperationCompleted == null))
            {
                this.obtenerTemaActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTemaActualOperationCompleted);
            }
            this.InvokeAsync("obtenerTemaActual", new object[0], this.obtenerTemaActualOperationCompleted, userState);
        }

        private void OnobtenerTemaActualOperationCompleted(object arg)
        {
            if ((this.obtenerTemaActualCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerTemaActualCompleted(this, new obtenerTemaActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerOperadorActual", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obtenerOperadorActual()
        {
            object[] results = this.Invoke("obtenerOperadorActual", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginobtenerOperadorActual(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("obtenerOperadorActual", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndobtenerOperadorActual(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void obtenerOperadorActualAsync()
        {
            this.obtenerOperadorActualAsync(null);
        }

        /// <remarks/>
        public void obtenerOperadorActualAsync(object userState)
        {
            if ((this.obtenerOperadorActualOperationCompleted == null))
            {
                this.obtenerOperadorActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerOperadorActualOperationCompleted);
            }
            this.InvokeAsync("obtenerOperadorActual", new object[0], this.obtenerOperadorActualOperationCompleted, userState);
        }

        private void OnobtenerOperadorActualOperationCompleted(object arg)
        {
            if ((this.obtenerOperadorActualCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerOperadorActualCompleted(this, new obtenerOperadorActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void obtenerConfiguracionActualCompletedEventHandler(object sender, obtenerConfiguracionActualCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerConfiguracionActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal obtenerConfiguracionActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void obtenerTemaActualCompletedEventHandler(object sender, obtenerTemaActualCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerTemaActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal obtenerTemaActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void obtenerOperadorActualCompletedEventHandler(object sender, obtenerOperadorActualCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerOperadorActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal obtenerOperadorActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}