//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="SmsWSServicePortBinding", Namespace="http://ws.me.org/")]
public partial class SmsWSServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback setSessionOperationCompleted;
    
    private System.Threading.SendOrPostCallback resetPasswordOperationCompleted;
    
    private System.Threading.SendOrPostCallback envioMensajesWebOperationCompleted;
    
    private System.Threading.SendOrPostCallback envioMensajesRsrvOperationCompleted;
    
    private System.Threading.SendOrPostCallback consultaEstadoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getMsgCounterOperationCompleted;
    
    private System.Threading.SendOrPostCallback getMsgMulCounterOperationCompleted;
    
    private System.Threading.SendOrPostCallback getHitCounterOperationCompleted;
    
    private System.Threading.SendOrPostCallback resetCountersOperationCompleted;
    
    private System.Threading.SendOrPostCallback getPasswordSizeOperationCompleted;
    
    /// <remarks/>
    public SmsWSServiceService() {
        this.Url = System.Configuration.ConfigurationManager.AppSettings["URL_SMS"].ToString();
    }
    
    /// <remarks/>
    public event setSessionCompletedEventHandler setSessionCompleted;
    
    /// <remarks/>
    public event resetPasswordCompletedEventHandler resetPasswordCompleted;
    
    /// <remarks/>
    public event envioMensajesWebCompletedEventHandler envioMensajesWebCompleted;
    
    /// <remarks/>
    public event envioMensajesRsrvCompletedEventHandler envioMensajesRsrvCompleted;
    
    /// <remarks/>
    public event consultaEstadoCompletedEventHandler consultaEstadoCompleted;
    
    /// <remarks/>
    public event getMsgCounterCompletedEventHandler getMsgCounterCompleted;
    
    /// <remarks/>
    public event getMsgMulCounterCompletedEventHandler getMsgMulCounterCompleted;
    
    /// <remarks/>
    public event getHitCounterCompletedEventHandler getHitCounterCompleted;
    
    /// <remarks/>
    public event resetCountersCompletedEventHandler resetCountersCompleted;
    
    /// <remarks/>
    public event getPasswordSizeCompletedEventHandler getPasswordSizeCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string setSession([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string session) {
        object[] results = this.Invoke("setSession", new object[] {
                    session});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsetSession(string session, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("setSession", new object[] {
                    session}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndsetSession(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void setSessionAsync(string session) {
        this.setSessionAsync(session, null);
    }
    
    /// <remarks/>
    public void setSessionAsync(string session, object userState) {
        if ((this.setSessionOperationCompleted == null)) {
            this.setSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetSessionOperationCompleted);
        }
        this.InvokeAsync("setSession", new object[] {
                    session}, this.setSessionOperationCompleted, userState);
    }
    
    private void OnsetSessionOperationCompleted(object arg) {
        if ((this.setSessionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.setSessionCompleted(this, new setSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string resetPassword() {
        object[] results = this.Invoke("resetPassword", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginresetPassword(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("resetPassword", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndresetPassword(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void resetPasswordAsync() {
        this.resetPasswordAsync(null);
    }
    
    /// <remarks/>
    public void resetPasswordAsync(object userState) {
        if ((this.resetPasswordOperationCompleted == null)) {
            this.resetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetPasswordOperationCompleted);
        }
        this.InvokeAsync("resetPassword", new object[0], this.resetPasswordOperationCompleted, userState);
    }
    
    private void OnresetPasswordOperationCompleted(object arg) {
        if ((this.resetPasswordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.resetPasswordCompleted(this, new resetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string envioMensajesWeb([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string session, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string telefono, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string mensaje) {
        object[] results = this.Invoke("envioMensajesWeb", new object[] {
                    session,
                    password,
                    telefono,
                    mensaje});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginenvioMensajesWeb(string session, string password, string telefono, string mensaje, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("envioMensajesWeb", new object[] {
                    session,
                    password,
                    telefono,
                    mensaje}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndenvioMensajesWeb(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void envioMensajesWebAsync(string session, string password, string telefono, string mensaje) {
        this.envioMensajesWebAsync(session, password, telefono, mensaje, null);
    }
    
    /// <remarks/>
    public void envioMensajesWebAsync(string session, string password, string telefono, string mensaje, object userState) {
        if ((this.envioMensajesWebOperationCompleted == null)) {
            this.envioMensajesWebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenvioMensajesWebOperationCompleted);
        }
        this.InvokeAsync("envioMensajesWeb", new object[] {
                    session,
                    password,
                    telefono,
                    mensaje}, this.envioMensajesWebOperationCompleted, userState);
    }
    
    private void OnenvioMensajesWebOperationCompleted(object arg) {
        if ((this.envioMensajesWebCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.envioMensajesWebCompleted(this, new envioMensajesWebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string envioMensajesRsrv([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string telefono, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string mensaje) {
        object[] results = this.Invoke("envioMensajesRsrv", new object[] {
                    usuario,
                    password,
                    telefono,
                    mensaje});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginenvioMensajesRsrv(string usuario, string password, string telefono, string mensaje, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("envioMensajesRsrv", new object[] {
                    usuario,
                    password,
                    telefono,
                    mensaje}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndenvioMensajesRsrv(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void envioMensajesRsrvAsync(string usuario, string password, string telefono, string mensaje) {
        this.envioMensajesRsrvAsync(usuario, password, telefono, mensaje, null);
    }
    
    /// <remarks/>
    public void envioMensajesRsrvAsync(string usuario, string password, string telefono, string mensaje, object userState) {
        if ((this.envioMensajesRsrvOperationCompleted == null)) {
            this.envioMensajesRsrvOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenvioMensajesRsrvOperationCompleted);
        }
        this.InvokeAsync("envioMensajesRsrv", new object[] {
                    usuario,
                    password,
                    telefono,
                    mensaje}, this.envioMensajesRsrvOperationCompleted, userState);
    }
    
    private void OnenvioMensajesRsrvOperationCompleted(object arg) {
        if ((this.envioMensajesRsrvCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.envioMensajesRsrvCompleted(this, new envioMensajesRsrvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string consultaEstado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string identificador) {
        object[] results = this.Invoke("consultaEstado", new object[] {
                    identificador});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginconsultaEstado(string identificador, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("consultaEstado", new object[] {
                    identificador}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndconsultaEstado(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void consultaEstadoAsync(string identificador) {
        this.consultaEstadoAsync(identificador, null);
    }
    
    /// <remarks/>
    public void consultaEstadoAsync(string identificador, object userState) {
        if ((this.consultaEstadoOperationCompleted == null)) {
            this.consultaEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaEstadoOperationCompleted);
        }
        this.InvokeAsync("consultaEstado", new object[] {
                    identificador}, this.consultaEstadoOperationCompleted, userState);
    }
    
    private void OnconsultaEstadoOperationCompleted(object arg) {
        if ((this.consultaEstadoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.consultaEstadoCompleted(this, new consultaEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getMsgCounter() {
        object[] results = this.Invoke("getMsgCounter", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetMsgCounter(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getMsgCounter", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetMsgCounter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getMsgCounterAsync() {
        this.getMsgCounterAsync(null);
    }
    
    /// <remarks/>
    public void getMsgCounterAsync(object userState) {
        if ((this.getMsgCounterOperationCompleted == null)) {
            this.getMsgCounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMsgCounterOperationCompleted);
        }
        this.InvokeAsync("getMsgCounter", new object[0], this.getMsgCounterOperationCompleted, userState);
    }
    
    private void OngetMsgCounterOperationCompleted(object arg) {
        if ((this.getMsgCounterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getMsgCounterCompleted(this, new getMsgCounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getMsgMulCounter() {
        object[] results = this.Invoke("getMsgMulCounter", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetMsgMulCounter(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getMsgMulCounter", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetMsgMulCounter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getMsgMulCounterAsync() {
        this.getMsgMulCounterAsync(null);
    }
    
    /// <remarks/>
    public void getMsgMulCounterAsync(object userState) {
        if ((this.getMsgMulCounterOperationCompleted == null)) {
            this.getMsgMulCounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMsgMulCounterOperationCompleted);
        }
        this.InvokeAsync("getMsgMulCounter", new object[0], this.getMsgMulCounterOperationCompleted, userState);
    }
    
    private void OngetMsgMulCounterOperationCompleted(object arg) {
        if ((this.getMsgMulCounterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getMsgMulCounterCompleted(this, new getMsgMulCounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getHitCounter() {
        object[] results = this.Invoke("getHitCounter", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetHitCounter(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getHitCounter", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetHitCounter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getHitCounterAsync() {
        this.getHitCounterAsync(null);
    }
    
    /// <remarks/>
    public void getHitCounterAsync(object userState) {
        if ((this.getHitCounterOperationCompleted == null)) {
            this.getHitCounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHitCounterOperationCompleted);
        }
        this.InvokeAsync("getHitCounter", new object[0], this.getHitCounterOperationCompleted, userState);
    }
    
    private void OngetHitCounterOperationCompleted(object arg) {
        if ((this.getHitCounterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getHitCounterCompleted(this, new getHitCounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string resetCounters() {
        object[] results = this.Invoke("resetCounters", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginresetCounters(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("resetCounters", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndresetCounters(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void resetCountersAsync() {
        this.resetCountersAsync(null);
    }
    
    /// <remarks/>
    public void resetCountersAsync(object userState) {
        if ((this.resetCountersOperationCompleted == null)) {
            this.resetCountersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetCountersOperationCompleted);
        }
        this.InvokeAsync("resetCounters", new object[0], this.resetCountersOperationCompleted, userState);
    }
    
    private void OnresetCountersOperationCompleted(object arg) {
        if ((this.resetCountersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.resetCountersCompleted(this, new resetCountersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.me.org/", ResponseNamespace="http://ws.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getPasswordSize() {
        object[] results = this.Invoke("getPasswordSize", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetPasswordSize(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getPasswordSize", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetPasswordSize(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getPasswordSizeAsync() {
        this.getPasswordSizeAsync(null);
    }
    
    /// <remarks/>
    public void getPasswordSizeAsync(object userState) {
        if ((this.getPasswordSizeOperationCompleted == null)) {
            this.getPasswordSizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPasswordSizeOperationCompleted);
        }
        this.InvokeAsync("getPasswordSize", new object[0], this.getPasswordSizeOperationCompleted, userState);
    }
    
    private void OngetPasswordSizeOperationCompleted(object arg) {
        if ((this.getPasswordSizeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPasswordSizeCompleted(this, new getPasswordSizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void setSessionCompletedEventHandler(object sender, setSessionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class setSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal setSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void resetPasswordCompletedEventHandler(object sender, resetPasswordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class resetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal resetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void envioMensajesWebCompletedEventHandler(object sender, envioMensajesWebCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class envioMensajesWebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal envioMensajesWebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void envioMensajesRsrvCompletedEventHandler(object sender, envioMensajesRsrvCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class envioMensajesRsrvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal envioMensajesRsrvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void consultaEstadoCompletedEventHandler(object sender, consultaEstadoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class consultaEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal consultaEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getMsgCounterCompletedEventHandler(object sender, getMsgCounterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getMsgCounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getMsgCounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getMsgMulCounterCompletedEventHandler(object sender, getMsgMulCounterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getMsgMulCounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getMsgMulCounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getHitCounterCompletedEventHandler(object sender, getHitCounterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getHitCounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getHitCounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void resetCountersCompletedEventHandler(object sender, resetCountersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class resetCountersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal resetCountersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getPasswordSizeCompletedEventHandler(object sender, getPasswordSizeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPasswordSizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPasswordSizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
